- internal/repository/contract_repository.go
> fix: solve error in query

- internal/domain/payments/payments.go
- internal/entity/contracts.go
- internal/usecase/contract/contract_usecase_test.go
- mocks/payments.go
> get contract

- internal/entity/contracts.go
- internal/repository/contract_repository.go
- internal/usecase/contract/contract_usecase.go
- internal/usecase/contract/contract_usecase_test.go
> fix: adding required on amount to create contract

- internal/domain/payments/payments.go
- internal/entity/contracts.go
- internal/usecase/contract/contract_usecase.go
- mocks/payments.go
> feat: fine to responsible when force cancel contract

- internal/handler/contract_handler.go
> feat: cancel contract route

- internal/repository/contract_repository.go
> fix: adjustment on query to cancel contract

- .gitignore
- cmd/api/admin/admin.go
- cmd/api/main.go
- cmd/consumers/uchiha_consumer.go
- config/config.go
- internal/domain/adapter/google_adapter.go
- internal/entity/school.go
- internal/handler/admin_handler.go
- internal/handler/auth_handler.go
- internal/handler/child_handler.go
- internal/handler/contract_handler.go
- internal/handler/driver_handler.go
- internal/handler/invites_handler.go
- internal/handler/maps_handler.go
- internal/handler/partner_handler.go
- internal/handler/responsible_handler.go
- internal/handler/school_handler.go
- internal/infra/app.go
- internal/usecase/helper.go
- internal/usecase/maps/maps_usecase.go
- internal/usecase/responsible/responsible_usecase.go
- scripts/producer.go
> remove unused blank rows

- cmd/api/v1/v1.go
- internal/repository/aws_repository.go
- internal/repository/child_repository.go
- internal/usecase/contract/contract_usecase.go
- internal/usecase/driver/driver_usecase.go
- internal/usecase/email/email_usecase.go
- internal/usecase/invite/invites_usecase.go
- internal/usecase/responsible/responsible_usecase.go
> refactor: remove unused blank rows

- .gitignore
- .golangci.yml
- Adicionando arquivo de linter para o Go.
> chore: add linter file

- internal/usecase/contract/contract_usecase.go
- internal/usecase/contract/contract_usecase_test.go
> refactor: change place of update contract when cancel contract

- cmd/api/v1/v1.go
- cmd/consumers/uchiha_consumer.go
- internal/domain/payments/payments.go
- internal/handler/contract_handler.go
- internal/repository/aws_repository.go
- internal/repository/contract_repository.go
- internal/usecase/contract/contract_usecase.go
- internal/usecase/contract/contract_usecase_test.go
- internal/usecase/invite/invites_usecase.go
- internal/usecase/maps/maps_usecase_test.go
- internal/usecase/responsible/responsible_usecase.go
> Grl cancel contract

- config/config.example.yaml
- internal/entity/child.go
- internal/entity/driver.go
- internal/entity/responsible.go
- internal/entity/school.go
- internal/repository/child_repository.go
- internal/repository/driver_repository.go
- internal/repository/responsible_repository.go
- internal/repository/school_repository.go
> Grl profile image

- cmd/api/v1/v1.go
- internal/handler/contract_handler.go
- internal/usecase/contract/contract_usecase.go
> Grl expire contract

- README.md
Criei uma descrição simples para que serve cada pasta da nossa arquitetura atual
[Github Issue - 95](https://github.com/venture-technology/venture/issues/95)
> feat: doc to new users of arch

- database/migrations/20250118000111_add-not-null-responsible-card.down.sql
- database/migrations/20250118000111_add-not-null-responsible-card.up.sql
- internal/entity/responsible.go
- internal/usecase/create_contract_usecase.go
- internal/usecase/create_responsible_usecase.go
Anteriormente quando um responsible era criado, em conjunto era criado um cliente na Stripe chamado de customer no código. E tinhamos outra rota que servia para adicionar cartão para esse cliente, conversando sobre os requisitos compreendemos que não é necessário uma rota e sim na criação da conta, solicitar o cartão.
https://github.com/venture-technology/venture/issues/100
Criando uma conta na plataforma
> feat: add credit card to customer

- database/migrations/20250118031509_car-integration-seats.up.sql
- internal/controller/driver_controller.go
- internal/controller/invites_controller.go
- internal/controller/kid_controller.go
- internal/controller/responsible_controller.go
- internal/controller/school_controller.go
- internal/entity/driver.go
- internal/infra/bucket/s3.go
- internal/usecase/create_driver_usecase.go
> driver s3 session fix

- internal/infra/persistence/partner_repository.go
- internal/usecase/driver_list_partners_usecase.go
- internal/usecase/school_list_partners_usecase.go
- internal/value/service.go
Esta PR procura solucionar alguns problemas entre parceiros (partners).
1. Anteriormente, quando um motorista ou escola buscava por parceiro, os registros eram encontrados. Mas, não populava as informações, como nome, endereço, etc. Esse foi um dos pontos resolvidos.
2. TInhamos um furo na regra de negócio. Contextualizando: Quando uma escola, manda um convite para um motorista, só aquela linha tendo o id da escola e do motorista poderiam ser registradas, afinal não faz sentido poder enviar dois convites. Sabendo disso, quando uma escola excluía um motorista da sua lista de parceiros, era impossível receber convidar novamente esse motorista. Afinal, a linha na tabela de invites continuava lá. Então, agora quando uma escola exclui um motorista, lá na tabela de convites, o convite que foi …
> fix partners error

- internal/controller/responsible_controller.go
- internal/domain/service/adapters/adapters.go
- internal/usecase/delete_responsible_usecase.go
Anteriormente, a exclusão de usuários na plataforma Stripe não era realizada de forma definitiva; contudo, atualmente, esse processo é efetuado de maneira formal.
#99 
1. crie um responsible 
2. deleta o responsible 
3. veja se deletou na stripe
> delete user from stripe 

- cmd/api/server/main.go
- cmd/api/server/routes/v1/main.go
- config/config.go
- database/migrations/20250210073601_add-column-contract-url.down.sql
- database/migrations/20250210073601_add-column-contract-url.up.sql
- go.mod
- go.sum
- internal/controller/contract_controller.go
- internal/domain/service/adapters/adapters.go
- internal/domain/service/agreements/agreements.go
- internal/domain/service/agreements/template/agreement.html
- internal/domain/service/agreements/types.go
- internal/entity/contract.go
- internal/infra/bucket/s3.go
- internal/infra/contracts/contracts.go
- internal/setup/setup.go
- internal/usecase/accept_contract_usecase.go
- internal/usecase/create_contract_usecase.go
- internal/value/service.go
Atualmente quando criavamos um contrato, não existia de fato um contrato, era apenas gerado uma nova linha no banco. 
Então agora, o fluxo é:
1. Primeiro recebemos uma criação de contrato
2. Quando esse contrato for assinado, iremos receber um webhook criando o contrato automaticamente (enviado pela dropbox)
Assim na criação de contrato, pegamos um html, colocamos todos os dados do contrato, transformamos ele em PDF, salvamos no nosso bucket e em seguida enviamos na requisição para criar o contrato la no dropbox, assim eles conseguem baixar o pdf e transformalo em contrato, em conjunto enviamos todos os dados do contrato como `Metadata` logo quando recebermos o webhook vamos ter todos os dados de maneira automática (etapa `2`).
#124 
Você pode tentar criar um novo motorista, responsible e …
> dropbox integration to create contracts 

- Makefile
- nginx.conf
Adicionando SSL em todos serviços que usamos.
#135
> feat: add ssl in server and our tools

- cmd/api/server/routes/v1/main.go
> feat: add route and log

- database/migrations/20250225031047_create-temp-contracts-table.down.sql
- database/migrations/20250225031047_create-temp-contracts-table.up.sql
- Adicionando tabela de contratos temporarios
#144 
Verifique no metabase
> feat: add table

- database/migrations/20250225133401_add-signature-request-id-column.down.sql
- database/migrations/20250225133401_add-signature-request-id-column.up.sql
- internal/domain/repository/temporary_contract_repository.go
- internal/domain/service/agreements/agreements.go
- internal/domain/service/agreements/types.go
- internal/entity/temporary_contract.go
- internal/infra/persistence/repositories.go
- internal/infra/persistence/temporary_contract_repository.go
- internal/setup/setup.go
- internal/usecase/create_contract_usecase.go
Agora estamos buscando o signed_url e o signed_id para guardar no banco. Para que o usuário possa verificar esses dados e assinar seu contrato, visitando o contrato direto da nossa plataforma ao invés de visitar seu email.
#145 
- Crie um contrato e verifique se você consegue criar mais de um dele com o mesmo Responsible e mesmo filho.
> using temp contracts table

- internal/domain/service/agreements/agreements.go
- internal/domain/service/agreements/types.go
deletei ordem de agreements e types 
#146
> refactor: delete order from agreements and types

- database/migrations/20250220024742_add-state-city.down.sql
- database/migrations/20250220024742_add-state-city.up.sql
- internal/entity/driver.go
- internal/entity/responsible.go
- internal/entity/school.go
- internal/usecase/get_driver_usecase.go
- internal/usecase/get_responsible_usecase.go
- internal/usecase/get_school_usecase.go
- internal/usecase/list_driver_usecase.go
- internal/usecase/list_school_usecase.go
- internal/value/service.go
adicionei estado e cidade para motorista, escola e responsável
#128
> -feat add city and state to driver and school

- cmd/api/server/routes/v1/main.go
- internal/controller/responsible__pending_controller.go
- internal/controller/temporary_contract_controller.go
- internal/domain/repository/temporary_contract_repository.go
- internal/infra/persistence/temporary_contract_repository.go
- internal/usecase/get_temp_contracts_usecase.go
- internal/value/service.go
implementei um controller para dar get em contratos temporários pendente
#149
> feat: show pending temporary contracts for responsible

- internal/domain/repository/driver_repository.go
- internal/domain/repository/invites_repository.go
- internal/domain/repository/partner_repository.go
- internal/domain/repository/responsible_repository.go
- internal/domain/repository/school_repository.go
- internal/domain/repository/temporary_contract_repository.go
- internal/infra/persistence/driver_repository.go
- internal/infra/persistence/invites_repository.go
- internal/infra/persistence/partner_repository.go
- internal/infra/persistence/responsible_repository.go
- internal/infra/persistence/school_repository.go
- internal/infra/persistence/temporary_contract_repository.go
- internal/usecase/calculate_price_drivers_usecase.go
- internal/usecase/driver_list_partners_usecase.go
- internal/usecase/get_temp_contracts_driver_usecase.go
- internal/usecase/get_temp_contracts_driver_usecase_test.go
- internal/usecase/get_temp_contracts_responsible_usecase.go
- internal/usecase/get_temp_contracts_responsible_usecase_test.go
- internal/usecase/list_driver_invite_usecase.go
- internal/usecase/list_driver_usecase.go
- internal/usecase/list_school_invites_usecase.go
- internal/usecase/school_list_partners_usecase.go
- mocks/driver_repository_mock.go
- mocks/responsible_repository_mock.go
- mocks/school_repository_mock.go
- mocks/temporary_contract_repository_mock.go
- alterar nomes que de repository, ex: de `findAllByCnh` para `getByDriver`, melhorando assim a compreensão do código e do que a função realiza 
#182
> refactor: improving repository name

- database/migrations/20250327030414_add-biography-and-description.down.sql
- database/migrations/20250327030414_add-biography-and-description.up.sql
- internal/entity/driver.go
- internal/value/service.go
adicionei biografia e descrição para o motorista  
#155
> feat: biography and description for driver

- Dockerfile
> fix: dockerfile error sql copy

- Dockerfile
> fix: config yaml error

- .github/workflows/qa-deploy.yml
- Makefile
> feat: prepare deploy using bot

- Makefile
resolvendo erro de deploy nos containers
> fix: makefile docker error

- cmd/api/server/routes/v1/main.go
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/controller/school_controller.go
adicionando swagger para escola
#238 
1. rode a aplicação e visite a rota do [swagger](http://localhost:9999/swagger/index.html#/)
> school swagger

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/controller/responsible_controller.go
adicionando responsible routes no swagger
#236 
1. rode a aplicação e visite a rota do [swagger](http://localhost:9999/swagger/index.html#/)
> add responsible to swagger

- cmd/api/server/routes/v1/main.go
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/controller/temporary_contract_controller.go
adicionando swagger nas rotas de temp contract
#254 
1. rode a aplicação e visite a rota do [swagger](http://localhost:9999/swagger/index.html#/)
> temp contract swagger

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/controller/contract_controller.go
- internal/controller/responsible_controller.go
- internal/controller/temporary_contract_controller.go
adição de rotas do swagger para contrato
#241 
1. rode a aplicação e visite a rota do [swagger](http://localhost:9999/swagger/index.html#/)
> contract swagger

- internal/usecase/driver_list_partners_usecase_test.go
adicionei teste unitário para driver list partners
#259
> test: add unit test for driver list partners

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- go.mod
- go.sum
- internal/controller/kid_controller.go
adicionei swagger para o kid controller 
#256
> feat: add swagger to kids

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/controller/driver_controller.go
adicionei swagger nas rotas do driver 
#237
> feat: add swagger to driver controller

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/controller/invites_controller.go
- internal/controller/partner_controller.go
adicionei swagger nas rotas do partner controller 
#239
> feat: add swagger to partner controller 

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/controller/invites_controller.go
adicionei swagger nas rotas de invite
#240
> feat: add swagger to invite controller

- Dockerfile
> fix: deploy docker error

- database/migrations/20250420062340_add-unique-email-constraint.down.sql
- database/migrations/20250420062340_add-unique-email-constraint.up.sql
- database/structure.sql
- adição de constraint nos emails para evitar duplicação
https://github.com/venture-technology/venture/issues/277
- procure algum email no banco e tente criar outra conta com o mesmo
> feat: add unique constraint to emails

- Makefile
- cmd/api/server/main.go
alteração do método de deploy, apenas atualizando compose ao invés do container por completo.
https://github.com/venture-technology/infrastructure/issues/4
- aprovando e rodando o pr como teste
> feat: change deploy method

- Makefile
> 🚨 fix: deploy compose error

- .github/workflows/staging-deploy.yml
- Makefile
> feat: add deploy qa

- Dockerfile
remove port of dockerfile to expose only at compose
> feat: remove port of dockerfile

- Makefile
- cmd/api/server/main.go
> feat: add custom command

- internal/controller/webhook_controller.go
> fix: test change status code

- .github/workflows/staging-deploy.yml
> ci: update pipeline to add uuid dispatcher

- internal/value/service.go
- adição do numero de telefone do responsavel na rota de get kid
> add number responible get kid

- cmd/api/administrator/main.go
- cmd/api/administrator/routes/admin/main.go
- internal/controller/admin_controller.go
- internal/controller/event_controller.go
- internal/controller/integrator_controller.go
nova rotas para api de admin, event e integrator
> feat: new microservice
